[project]
name = "meta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "RAHUL G", email = "rahulgaur608@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.128.8",
    "openai>=2.30.0",
    "pydantic>=2.12.5",
    "uvicorn[standard]>=0.39.0",
]

[project.scripts]
server = "app:main"

[build-system]
requires = ["uv_build>=0.11.0,<0.12.0"]
build-backend = "uv_build"
